import { Badge } from "@uxin/ui";
import {
  Calendar,
  ClipboardList,
  CheckCircle2,
  AlertCircle,
  PlayCircle,
  HelpCircle,
} from "lucide-react";
import { parseStructuredContent } from "../lib/utils";
import { Response } from "./response";

interface ReportTemplateProps {
  content: string;
}

export function ReportTemplate({ content }: ReportTemplateProps) {
  let data = {
    title: "",
    type: "Daily",
    date: "",
    summary: "",
    problems: "",
    plans: "",
    assistance: "",
  };

  try {
    data = parseStructuredContent(content);
  } catch (e) {
    return (
      <div className="max-w-4xl mx-auto p-10 bg-white shadow-md my-4 min-h-[1000px]">
        <div className="prose prose-slate max-w-none dark:prose-invert">
          <Response>{content}</Response>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto my-8 bg-white dark:bg-zinc-900 shadow-2xl border-t-4 border-t-green-500 rounded-b-xl overflow-hidden min-h-[1000px]">
      <div className="p-10 border-b bg-muted/5">
        <div className="flex justify-between items-center mb-8">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-500 text-white rounded-lg">
              <ClipboardList className="w-6 h-6" />
            </div>
            <Badge variant="secondary" className="font-bold tracking-widest text-xs px-3 py-1">
              {data.type.toUpperCase()} REPORT
            </Badge>
          </div>
          <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
            <Calendar className="w-4 h-4 text-green-500" />
            {data.date || "Today"}
          </div>
        </div>

        <h1 className="text-4xl font-black tracking-tight text-foreground mb-4">
          {data.title || "Untitled Report"}
        </h1>
        <div className="w-20 h-1.5 bg-green-500 rounded-full" />
      </div>

      <div className="p-10 space-y-12">
        {data.summary && (
          <section className="space-y-4">
            <div className="flex items-center gap-2 text-xl font-bold text-foreground pb-2 border-b">
              <CheckCircle2 className="w-6 h-6 text-green-500" />
              <h2>工作总结 (Summary)</h2>
            </div>
            <div className="prose prose-zinc lg:prose-lg max-w-none dark:prose-invert">
              <Response>{data.summary}</Response>
            </div>
          </section>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          {data.problems && (
            <section className="space-y-4">
              <div className="flex items-center gap-2 text-xl font-bold text-foreground pb-2 border-b border-amber-200">
                <AlertCircle className="w-6 h-6 text-amber-500" />
                <h2>遇到问题 (Problems)</h2>
              </div>
              <div className="prose prose-zinc max-w-none dark:prose-invert">
                <Response>{data.problems}</Response>
              </div>
            </section>
          )}

          {data.plans && (
            <section className="space-y-4">
              <div className="flex items-center gap-2 text-xl font-bold text-foreground pb-2 border-b border-blue-200">
                <PlayCircle className="w-6 h-6 text-blue-500" />
                <h2>下一步计划 (Plans)</h2>
              </div>
              <div className="prose prose-zinc max-w-none dark:prose-invert">
                <Response>{data.plans}</Response>
              </div>
            </section>
          )}
        </div>

        {data.assistance && (
          <section className="space-y-4 p-6 bg-purple-50 dark:bg-purple-900/10 rounded-2xl border border-purple-100 dark:border-purple-800">
            <div className="flex items-center gap-2 text-xl font-bold text-purple-700 dark:text-purple-300 pb-2 border-b border-purple-200 dark:border-purple-800">
              <HelpCircle className="w-6 h-6" />
              <h2>需要协助 (Assistance)</h2>
            </div>
            <div className="prose prose-purple max-w-none dark:prose-invert pt-4">
              <Response>{data.assistance}</Response>
            </div>
          </section>
        )}
      </div>

      <div className="p-10 border-t bg-muted/5 flex justify-center">
        <div className="text-xs text-muted-foreground font-medium italic">
          Generated by UXIN AI Assistant • {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
