version: "3"
services:
  frps:
    image: registry.cn-hangzhou.aliyuncs.com/kyrie/frps:0.51.0
    container_name: uxin-frps
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./docker/frps.ini:/etc/frp/frps.ini:ro
    command: frps -c /etc/frp/frps.ini
