const TOOL_PERMISSION_MAP: Record<string, string> = {
  project_create: "project.write",
  project_query: "project.read",
  task_create: "task.write",
  task_list: "task.read",
  task_update_status: "task.write",
  requirement_create: "requirement.write",
  milestone_monitor: "milestone.read",
  defect_create: "defect.write",
  risk_create: "risk.write",
  collaboration_dispatch: "collaboration.write",
  collaboration_sync: "collaboration.write",
  quotation_create: "quotation.write",
  transaction_create: "transaction.write",
  service_create: "service.write",
  skill_analyzer: "analysis.read",
  marketplace_integrator: "marketplace.read",
  compliance_checker: "compliance.read",
  growth_strategy_analyzer: "analysis.read",
  ux_design_reviewer: "analysis.read",
  devops_pipeline_optimizer: "analysis.read",
  // Test Case Management
  test_case_create: "test.write",
  test_case_query: "test.read",
  test_case_get: "test.read",
  test_case_update: "test.write",
  test_case_delete: "test.write",
  test_case_submit_review: "test.write",
  test_case_review: "test.write",
  test_case_execute: "test.write",
  test_case_get_executions: "test.read",
  test_case_stats: "test.read",
  test_case_batch_create: "test.write",
};

export const resolveMcpPermission = (tool: string) =>
  TOOL_PERMISSION_MAP[tool] ?? "tool.execute";

export const resolveDefaultAllowlist = () => [
  "project_create",
  "project_query",
  "task_create",
  "task_list",
  "task_update_status",
  "milestone_create",
  "milestone_monitor",
  "requirement_create",
  "defect_create",
  "risk_create",
  "collaboration_dispatch",
  "skill_analyzer",
  "talent_match",
  "resume_create",
  "freelancer_register",
  "service_create",
  "transaction_create",
  "contract_create",
  "marketplace_integrator",
  "compliance_checker",
  "growth_strategy_analyzer",
  "ux_design_reviewer",
  "devops_pipeline_optimizer",
  "agent_collaboration_plan",
  "agent_collaboration_start",
  "document_query",
  // Test Case Management
  "test_case_create",
  "test_case_query",
  "test_case_get",
  "test_case_update",
  "test_case_delete",
  "test_case_submit_review",
  "test_case_review",
  "test_case_execute",
  "test_case_get_executions",
  "test_case_stats",
  "test_case_batch_create",
  // Document Management
  "document_create",
  "document_get",
  "document_update",
  "document_delete",
  "document_review",
  "document_stats",
  // Iteration Management
  "iteration_create",
  "iteration_query",
  "iteration_get",
  "iteration_list",
  "iteration_overview",
  "iteration_stats",
  "iteration_workitems",
  "iteration_workitem_stats",
  "iteration_plan",
  "iteration_update",
  "iteration_delete",
];
