import React, { useState, useEffect } from "react";
import { createRoot } from "react-dom/client";
import { ProjectManagerCard } from "./project-manager-card";

// 1. 定义组件注册表 (Component Registry)
// 在实际应用中，这可以通过动态 import() 或远程组件加载来实现
const COMPONENT_REGISTRY: Record<string, React.ComponentType<any>> = {
  "project-manager-card": ProjectManagerCard,
};

// 2. 模拟工具调用结果 (Simulated Tool Output)
// 这代表 Agent 执行 "Get Project JSON" 后返回的数据
const MOCK_TOOL_OUTPUT = {
  toolName: "project-manager:Get Project JSON",
  componentName: "project-manager-card", // 对应 SKILL.md 中的 metadata.ui.component
  data: {
    requirements: [
      {
        id: "用户登录",
        content:
          "# 用户登录\n用户需要通过邮箱和密码登录系统。\n\n## 验收标准\n- [ ] 支持邮箱格式校验\n- [ ] 密码强度检查",
      },
      { id: "任务看板", content: "# 任务看板\n支持拖拽排序的任务管理界面。" },
    ],
    tasks: [
      { id: "1715001", description: "设计登录页面 UI", status: "COMPLETED" },
      { id: "1715002", description: "实现 JWT 认证接口", status: "IN_PROGRESS" },
      { id: "1715003", description: "前端对接登录 API", status: "PENDING" },
      { id: "1715004", description: "编写单元测试", status: "PENDING" },
    ],
  },
};

// 3. Artifact 渲染器组件 (The Artifact Renderer)
const ArtifactRenderer = () => {
  const [activeArtifact, setActiveArtifact] = useState<typeof MOCK_TOOL_OUTPUT | null>(null);

  // 模拟：监听工具调用事件
  useEffect(() => {
    // 假设这是从 Agent 消息流中捕获到的事件
    const handleToolResult = () => {
      console.log("收到工具调用结果，准备渲染 Artifact...");
      // 在真实场景中，这里会解析 JSON 字符串
      setActiveArtifact(MOCK_TOOL_OUTPUT);
    };

    // 延迟 1 秒模拟网络请求
    setTimeout(handleToolResult, 1000);
  }, []);

  if (!activeArtifact) {
    return <div className="p-4 text-gray-500">等待 Agent 生成数据...</div>;
  }

  // 动态查找组件
  const Component = COMPONENT_REGISTRY[activeArtifact.componentName];

  if (!Component) {
    return <div className="text-red-500">错误：找不到组件 {activeArtifact.componentName}</div>;
  }

  return (
    <div className="artifact-container border rounded-lg shadow-lg overflow-hidden bg-white my-4">
      <div className="bg-gray-100 px-4 py-2 border-b text-xs text-gray-500 flex justify-between">
        <span>Generated by: {activeArtifact.toolName}</span>
        <span>Artifact UI</span>
      </div>
      <div className="p-0">
        {/* 核心：将 JSON 数据注入组件 */}
        <Component data={activeArtifact.data} />
      </div>
    </div>
  );
};

// 4. 挂载到页面
const rootElement = document.getElementById("root");
if (rootElement) {
  const root = createRoot(rootElement);
  root.render(<ArtifactRenderer />);
}
